require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'textscanner' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'lottie-react-native', :path => '../node_modules/lottie-react-native'


  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'react-native-safe-area-context', :path => '../node_modules/react-native-safe-area-context'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBML', :path => '../node_modules/@react-native-firebase/ml'


  pod 'RNCMaskedView', :path => '../node_modules/@react-native-community/masked-view'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  target 'textscannerTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'textscanner-tvOS' do
  # Pods for textscanner-tvOS

  target 'textscanner-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
